In [16]:
import torch

### batchnorm作用维度为第一个非batch维度，即dim=1的维度；

## batchnorm1d

In [2]:

input = torch.rand(3,5)
bn1d = torch.nn.BatchNorm1d(5)

In [3]:
input

tensor([[0.6512, 0.3209, 0.3235, 0.7692, 0.3931],
        [0.6488, 0.7993, 0.0065, 0.5221, 0.6520],
        [0.5915, 0.2879, 0.8150, 0.7181, 0.5326]])

In [4]:
bn1d_res = bn1d(input)
bn1d_res

tensor([[ 0.7455, -0.6353, -0.1749,  0.9327, -1.2547],
        [ 0.6586,  1.4117, -1.1278, -1.3862,  1.1913],
        [-1.4041, -0.7765,  1.3027,  0.4535,  0.0634]],
       grad_fn=<NativeBatchNormBackward0>)

In [8]:
torch.mean(bn1d_res, axis=0)

tensor([ 1.2716e-06,  3.9736e-08,  0.0000e+00,  0.0000e+00, -1.5895e-07],
       grad_fn=<MeanBackward1>)

In [10]:
torch.std(bn1d_res, axis=0, unbiased=False)

tensor([0.9935, 0.9999, 1.0000, 0.9996, 0.9996], grad_fn=<StdBackward0>)

## batchnorm2d

In [12]:
input = torch.rand(2,4,2,2)
bn2d = torch.nn.BatchNorm2d(4)

In [13]:
input

tensor([[[[0.2021, 0.1355],
          [0.0620, 0.9071]],

         [[0.6035, 0.4273],
          [0.7865, 0.9834]],

         [[0.2851, 0.7727],
          [0.7548, 0.9020]],

         [[0.6641, 0.9390],
          [0.1686, 0.2608]]],


        [[[0.1323, 0.3708],
          [0.8826, 0.0508]],

         [[0.1615, 0.3730],
          [0.5264, 0.8927]],

         [[0.6919, 0.0089],
          [0.5365, 0.9684]],

         [[0.5813, 0.5798],
          [0.2490, 0.5596]]]])

In [15]:
bn2d_res = bn2d(input)
bn2d_res

tensor([[[[-0.4242, -0.6245],
          [-0.8459,  1.6994]],

         [[ 0.0352, -0.6391],
          [ 0.7355,  1.4890]],

         [[-1.0847,  0.5183],
          [ 0.4595,  0.9435]],

         [[ 0.6785,  1.8173],
          [-1.3737, -0.9920]]],


        [[[-0.6344,  0.0839],
          [ 1.6255, -0.8798]],

         [[-1.6560, -0.8467],
          [-0.2599,  1.1420]],

         [[ 0.2527, -1.9930],
          [-0.2582,  1.1619]],

         [[ 0.3356,  0.3293],
          [-1.0408,  0.2458]]]], grad_fn=<NativeBatchNormBackward0>)

In [17]:
line1 = [-0.4242, -0.6245, -0.8459,  1.6994, -0.6344,  0.0839, 1.6255, -0.8798]
import numpy as np

In [18]:
np.mean(line1)

-2.7755575615628914e-17

In [19]:
np.std(line1)

0.9999533689127709

## batchnorm3d

In [24]:
input = torch.rand(2,3,2,1,2)
bn3d = torch.nn.BatchNorm3d(3)

In [25]:
input

tensor([[[[[0.8472, 0.8452]],

          [[0.1728, 0.0856]]],


         [[[0.5020, 0.1975]],

          [[0.5831, 0.4014]]],


         [[[0.1179, 0.6056]],

          [[0.8159, 0.5325]]]],



        [[[[0.0660, 0.1115]],

          [[0.5196, 0.7767]]],


         [[[0.3978, 0.5254]],

          [[0.5931, 0.4355]]],


         [[[0.9594, 0.6808]],

          [[0.2689, 0.9139]]]]])

In [27]:
bn3d_res = bn3d(input)
bn3d_res

tensor([[[[[ 1.2541,  1.2483]],

          [[-0.7638, -1.0247]]],


         [[[ 0.3955, -2.1381]],

          [[ 1.0703, -0.4416]]],


         [[[-1.7652, -0.0225]],

          [[ 0.7293, -0.2836]]]],



        [[[[-1.0835, -0.9474]],

          [[ 0.2738,  1.0433]]],


         [[[-0.4719,  0.5901]],

          [[ 1.1533, -0.1576]]],


         [[[ 1.2419,  0.2463]],

          [[-1.2257,  1.0795]]]]], grad_fn=<NativeBatchNormBackward0>)

In [28]:
line1 = [1.2541,  1.2483, -0.7638, -1.0247, -1.0835, -0.9474, 0.2738,  1.0433]

In [29]:
np.mean(line1)

1.2499999999970868e-05

In [30]:
np.std(line1)

0.999962534845056